title: Książki Przydatne Przyszłym Podróżnikom
theme: minima

minima:
  nav_pages:
    - 01_index.md
    - 02_o-nas.md
    - 03_przewodniki.md
    - 04_Dania.md
    - 05_Portugalia.md
    - 06_Węgry.md
